# Generated by Django 4.2.4 on 2023-08-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=400)),
                ('manufaturer', models.CharField(max_length=400)),
                ('role', models.CharField(max_length=400)),
                ('service', models.CharField(max_length=400)),
                ('dimensions', models.CharField(max_length=400)),
                ('max_speed', models.IntegerField()),
                ('cruise_speed', models.IntegerField()),
                ('range', models.IntegerField()),
                ('capacity', models.TextField(max_length=2000)),
            ],
        ),
    ]
