# Generated by Django 4.2.4 on 2023-08-14 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_manufaturer_aircraft_manufacturer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintainance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('maintain', models.CharField(choices=[('R', 'Repairs'), ('F', 'Re-fuel'), ('A', 'Re-arm'), ('S', 'Re-supply')], default='R', max_length=1)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.aircraft')),
            ],
        ),
    ]
